name: "Build Docker Image"
on:
  push:
    branches:
      - main
defaults:
  run:
    shell: bash

jobs:
  
  build-and-push:
    name: "Build and push Docker image"
    runs-on: ubuntu-latest
    env: 
      IMAGE_NAME: 'cheqd/cheqd-faucet'
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
          version: latest
      
      - name: Configure Docker image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            registry.digitalocean.com/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,format=long
      
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.faucet
          load: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=min

      - name: Install DigitalOcean CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DOCR
        run: doctl registry login --expiry-seconds 600

      - name: Push staging image to DOCR
        run: docker image push --all-tags registry.digitalocean.com/${{ env.IMAGE_NAME }}
